[package]
name = "mdnya-hl-bash-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20"
mdnya-hl = { path = "../../mdnya-hl", features=["generate"] }

[build-dependencies]
cc = "1"