[package]
name = "mdnya-hl-bash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
tree-sitter = "0.20"
mdnya-hl = { path = "../../mdnya-hl" }

[build-dependencies]
cc = "1"

[features]
default = ["static"]
dynamic = [ "mdnya-hl/dynamic" ]
static = []