[package]
name = "mdnya-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
tree-sitter = "0.20.9"
tree-sitter-highlight = "0.20.1"
regex = "1"
lazy_static = "1.4.0"
html-escape = "0.2.11"

mdnya = { path = "../mdnya" }

mdnya-hl-rust = { path = "../mdnya-hl-langs/rust" }
mdnya-hl-bash = { path = "../mdnya-hl-langs/bash" }
mdnya-hl-csharp = { path = "../mdnya-hl-langs/csharp" }

[build-dependencies]
cc = "*"